### ISSUE TITLE
What is the estimated mean flow miu?

### ISSUE THREAD

**Issue by 07hyx06** [PruneTruong/DenseMatching#1]
and what's the relationship between the estimated flow miu and the output flow y..?

**Comment by PruneTruong** [comment]
Hi, I am very sorry about the late answer. So while non-probabilistic methods will predict a flow vector y for each pixel location of the reference image as only output (a single flow field), in PDC-Net, we predict for each pixel location the parameters of the conditional probability density of the flow vector y given the input images. This probability density distribution is parametrized as a constrained mixture of M Laplace distributions. Its parameters (which are predicted by the network for each pixel) are a mean miu and M variance and alpha parameters. The mean miu is used as the estimated flow vector in the case. 
I hope that helps.
