### ISSUE TITLE
About Scannet Training

### ISSUE THREAD

**Issue by zwyking** [PruneTruong/DenseMatching#12]
Hi, I recently trained the PDCNet on Scannet dataset but get a worse result. The flow estimation is regular while the probabilistic map is predicted wrongly. Is it something different between scannet and Megadepth?

**Comment by PruneTruong** [comment]
Hi, I haven't tried training on Scannet but i do not see obvious reasons with it wouldn't work there. Did you train on only sparse gt from scannet or on a combination of scannet and synthetic dense data? We found that having synthetic dense ground-truth is very important to regularize the uncertainty prediction.
