### ISSUE TITLE
Training on my own Data

### ISSUE THREAD

**Issue by davidz123** [PruneTruong/DenseMatching#13]
https://github.com/PruneTruong/GLU-Net/issues/11#issuecomment-951617806

**Comment by PruneTruong** [comment]
Hi, as I said, i did not generate the csv files myself. In this example https://github.com/PruneTruong/DenseMatching/blob/main/train_settings/GLUNet/train_GLUNet_with_synthetically_generated_data.py, I generate random flow fields on the fly, and apply them to an image, to create a training image pair. If you wanted to create a csv file instead, you could log the values of the created intermediate theta in the function 'SynthecticAffHomoTPSTransfo', which are in my case used to create a flow field.
