### ISSUE TITLE
About the theta of synthetic data warping

### ISSUE THREAD

**Issue by zwyking** [PruneTruong/DenseMatching#14]
Hi, I'm curious about that how to generate the theta for homo/tps/affine. Where should I find the code of the part?

Thanks.

**Comment by PruneTruong** [comment]
Hi, in this example https://github.com/PruneTruong/DenseMatching/blob/main/train_settings/GLUNet/train_GLUNet_with_synthetically_generated_data.py, I generate random flow fields on the fly, and apply them to an image, to create a training image pair.

**Comment by zwyking** [comment]
Ok, thanks for your reply!
