### ISSUE TITLE
PDCNet: the fixed σ12 = β1− = β1+ = 1

### ISSUE THREAD

**Issue by zwyking** [PruneTruong/DenseMatching#16]
Hi,
Thanks for your excellent work. I would like to know if all the experiments in the paper are based on the fixed  settings.

Thanks.

**Comment by PruneTruong** [comment]
Hi, 

Thanks! Yes all the experiments with PDCNet are with this fixed setting. For the ablation study though, we also tried the first component variance between 0 and 1, you can check the results in the paper.

**Comment by zwyking** [comment]
Ok! Thanks for your reply~
