### ISSUE TITLE
Some questions about the supervise loss

### ISSUE THREAD

**Issue by JiangHai0929** [PruneTruong/DenseMatching#17]
Hi, I have some questions about the supervise loss as follows;
_ss_loss_o, ss_stats_o = self.objective(estimated_flow_target_prime_to_target_directly, mini_batch['flow_map'], mask=mini_batch['mask']_,
the mini_batch['flow_map'] is the ground-truth flow you generate in the online_triplet_creation.py (_flow_gt = self.synthetic_flow_generator(mini_batch=mini_batch, training=training, net=net)_) and the target image prime is warped by using the flow_gt, so the mini_batch['flow_map'] should be _flow_target_to_target_prime_directly_, why you caclulate the L1 distance between  _estimated_flow_target_prime_to_target_directly and mini_batch['flow_map']_ rather than the distance between  _estimated_flow_target_to_target_prime_directly and mini_batch['flow_map']_.
Thanks, Looking forward to your reply!

**Comment by PruneTruong** [comment]
Hey, so I assume you answered your question? :)

**Comment by JiangHai0929** [comment]
yes, i made a mistake, thank you!
