### ISSUE TITLE
Details of MegaDepth for WarpC training.

### ISSUE THREAD

**Issue by wdmwhh** [PruneTruong/DenseMatching#20]
Thanks for your great works.
I fail to find 
```
'train_split': 'train_scenes_MegaDepth.txt',
'train_debug_split': 'train_debug_scenes_MegaDepth.txt',
'val_split': 'validation_scenes_MegaDepth.txt',
```
these files. Could you release more details to preprocess MegaDepth Dataset?

**Comment by PruneTruong** [comment]
Hi, the files are in the datasets/MegaDepth folder (https://github.com/PruneTruong/DenseMatching/tree/main/datasets/MegaDepth). The train_debug_split is just one scene is use to debug on my computer. You can train WarpC-GLUNet by running this file (https://github.com/PruneTruong/DenseMatching/blob/main/train_settings/WarpC/train_WarpC_GLUNet_stage1.py).

**Comment by wdmwhh** [comment]
Thanks for your guidance. I am careless.
