### ISSUE TITLE
about MegaDepth

### ISSUE THREAD

**Issue by menghuaa** [PruneTruong/DenseMatching#21]
Hi，how much memory storage is required for the dataset MegaDepth? How much memory is required for training the WarpC model on the dataset MegaDepth?

**Comment by PruneTruong** [comment]
Hi, sorry for the delay. If you want to store all MegaDepth annotations in memory, then it takes about 50G. But otherwise, you can load the necessary annotations at each iteration instead, which is much cheaper memory wise.
