### ISSUE TITLE
ModuleNotFoundError: No module named 'third_party'

### ISSUE THREAD

**Issue by yuanzhougege** [PruneTruong/DenseMatching#24]
`Traceback (most recent call last):
  File "test_models.py", line 8, in <module>
    from model_selection import select_model
  File "/DenseMatching/model_selection.py", line 1, in <module>
    from models.GLUNet.GLU_Net import GLUNetModel
  File "/DenseMatching/models/GLUNet/GLU_Net.py", line 7, in <module>
    from models.base_matching_net import BaseGLUMultiScaleMatchingNet, set_glunet_parameters
  File "/DenseMatching/models/base_matching_net.py", line 12, in <module>
    from third_party.GOCor.GOCor.global_gocor_modules import GlobalGOCorWithFlexibleContextAwareInitializer
ModuleNotFoundError: No module named 'third_party'`

I meet this error when testing on my own pairs, could you tell me why? Thanks!

**Comment by PruneTruong** [comment]
Hi, did you pull the required third party packages with

git submodule update --init --recursive
git submodule update --recursive --remote

**Comment by PruneTruong** [comment]
I am closing due to lack of recent activity. Feel free to reopen if you still have a question.
