### ISSUE TITLE
About the download link

### ISSUE THREAD

**Issue by hhuxuchang** [PruneTruong/DenseMatching#25]
Thanks,

MegaDepth
We use the reconstructions provided in the [D2-Net repo](https://github.com/mihaidusmanu/d2-net). You can download the undistorted reconstructions and aggregated scene information folder directly [here - Google Drive](https://drive.google.com/drive/folders/1hxpOsqOZefdrba_BqnW490XpNX_LgXPB).

However, this link is filed to open,
could you provided it again.

**Comment by PruneTruong** [comment]
Hi, unfortunately the link I had put is the one from the D2-Net repo. If it doesn't work anymore, there is nothing I can do. You need to address this directly with the author of D2-Net.
