### ISSUE TITLE
'EnvironmentSettings' object has no attribute 'PFPascal_tar'

### ISSUE THREAD

**Issue by iron-man45** [PruneTruong/DenseMatching#27]
python run_training.py PWarpC train_weakly_supervised_PWarpC_SFNet_spair_from_pfpascal. this problem occur when I run the above order.

**Comment by PruneTruong** [comment]
Hi sorry about that, you can just remove this line with prepare_data completely. I have it because in my cluster, I need to store the data as tar, which are unzipped automatically in the prepare_data function, and I forgot to remove it from the release code

**Comment by PruneTruong** [comment]
This should be fixed in the released code now. Thanks for pointing that out.
