### ISSUE TITLE
Why is the radius R equal to 1 in the confidence estimation?

### ISSUE THREAD

**Issue by syqzdy** [PruneTruong/DenseMatching#3]

**Comment by martin-danelljan** [comment]
Hi. We used R=1 pixel for simplicity. If i remember correctly, larger theresholds gave similar results for eg Megadepth (@PruneTruong would know more). If you care more about robustness than small errors, a larger radius would be better.

**Comment by PruneTruong** [comment]
Yes, setting R=3 or R=5 gave similar results so we used R=1 everywhere for simplicity!
