### ISSUE TITLE
Training code release date

### ISSUE THREAD

**Issue by masakistan** [PruneTruong/DenseMatching#4]
Thanks so much for this great work! Do you have an estimated date for the training code to be released?

Thanks!

**Comment by PruneTruong** [comment]
Hi, thanks for your interest in our work! Training code should be out by the end of the month :) Sorry for the delay.

**Comment by PruneTruong** [comment]
Training code is here! Please if you use it, let me know if there is an issue. Thanks!

**Comment by masakistan** [comment]
Thanks so much @PruneTruong !
