### ISSUE TITLE
Questions about testing my own images

### ISSUE THREAD

**Issue by Nianzhen-GU** [PruneTruong/DenseMatching#7]
Hi! I'm trying to use the PDC-Net to warp my own pair images, which are shown below.
![chair2](https://user-images.githubusercontent.com/80320541/133539916-9233fb67-ba88-4316-829c-5f525a34a370.png)
![chair5](https://user-images.githubusercontent.com/80320541/133539937-d05e1314-a905-4b45-8803-a248a6fa874c.png)
However, there is a problem said 
<img width="1206" alt="Screen Shot 2021-09-15 at 10 31 37 PM" src="https://user-images.githubusercontent.com/80320541/133540039-4fb62706-a06e-45b6-b85f-a2c03e6a8527.png">
I don't know how to solve it. I will very appreciate it if you could answer me. Thanks!

**Comment by PruneTruong** [comment]
Hi, what are the sizes of the original image, if you print them just after reading? We expect rgb images.

**Comment by Nianzhen-GU** [comment]
They are both 541x375 and RGB images.

**Comment by PruneTruong** [comment]
Hi, your images were not RGB, they have 4 channels (print the shape after simple reading to check). Nevertheless, i made a modification in the reading of the images so it supports 4 channels and gray scale images.

**Comment by Nianzhen-GU** [comment]
It works. Thanks a lot! Also, is it possible to only get the warped image rather than several images bond together?

**Comment by USTC-wlsong** [comment]
> Hi, your images were not RGB, they have 4 channels (print the shape after simple reading to check). Nevertheless, i made a modification in the reading of the images so it supports 4 channels and gray scale images.

I have the same problem. The images is 4 channels by imageio.imread, but 3 channels by cv2.imread.
