### ISSUE TITLE
Code release about Warp Consistency for Unsupervised Learning of Dense Correspondences

### ISSUE THREAD

**Issue by SunghwanHong** [PruneTruong/DenseMatching#8]
Hi !
Thanks for sharing such wonderful works since GLAMpoints. All the papers and code greatly helped my research, which I am highly appreciated. I'm looking forward to see the next paper you will release in the near future (perhaps for ECCV).. 

I have a question about the newly accepted paper by ICCV'21. Currently, the code seems to be not released yet. If it doesn't bother you, can i please know when will the code be available? 

Thanks

**Comment by PruneTruong** [comment]
Hi, thanks for these kind words! I plan on releasing the trained models for the ICCV conference. As for the training code, it might take a bit longer since i have to clean it and i am currently quite busy for cvpr, i will let you know when it is ready. Thanks for your patience and understanding.
