### ISSUE TITLE
Some questions about the warped image

### ISSUE THREAD

**Issue by Nianzhen-GU** [PruneTruong/DenseMatching#9]
1. Is it possible to only get the warped image rather than several images bond together? 
2. Is the information of the warped image, say resolution, completely comes from the query image? I mean the reference image doesn't contribute any additional information to the final result.

**Comment by PruneTruong** [comment]
Hi, 
1. Sure, i updated the test_models.py file so you can add option --save_ind_images True, which will retrieve original images and warped images. You can remove the lines about the reference and query there if you don't want them. You could also save the confident mask if you want. 
2. the resolution of the warped image completely comes from the reference image. You are estimating a flow from every single pixel of the reference towards the query. This flow is subsequently used to warp the query. If you resize the reference (not the query, then it would require some scaling), you could however resize the flow like you would resize the reference image.

**Comment by Nianzhen-GU** [comment]
I'm sorry, I didn't find "--save_ind_images" in test_models.py.

**Comment by PruneTruong** [comment]
Ah my bad, I forgot to push and only committed. It's there now

**Comment by Nianzhen-GU** [comment]
I set --save_ind_images = True and it works. However, I still want the mask exists, what should I do?

**Comment by PruneTruong** [comment]
You can also save the confidence_map or confident_mask depending what you want, just like the warped image is saved.
